### PR TITLE
Handle failed authentication attempts

### PR DESCRIPTION
**Pull request by dmsnell**
Previously when making a login attempt for a wrong username or password, the server was responding with plain text which threw an exception when attempting to create the user object. This is because `JSON.parse()` couldn't handle it.

**Bad username** - `unknown username: bad-email@example.com`
**Bad password** - `invalid password`

Now we return `null` in these cases to indicate the failures.

cc: @roundhill @beaucollins

### CODE REVIEW

**Comment by beaucollins** [comment]
Looks like our `.eslintrc` is failing due to a missing npm module:
```
Error: Cannot find module 'estraverse-fb'
```

**Comment by dmsnell** [comment]
what a bum @beaucollins ! thanks for your responsiveness. are things broken in **master** then too? should I try and fix/update this inside this PR?

**Comment by dmsnell** [comment]
@beaucollins https://github.com/eslint/eslint/issues/5476

should we pin our `babel-eslint` to a working version? I'm not sure how/where to configure travis-ci

**Comment by beaucollins** [comment]
@dmsnell :+1: to ship this

**Pull request merged**
