### PR TITLE
Conforming to organization JS style guide

### PR DESCRIPTION
**Pull request by beaucollins**
Let's make this JS like the rest of Automattic's JS.

### CODE REVIEW

**Comment by beaucollins** [comment]
```
eslint lib/
✖ 5905 problems (116 errors, 5789 warnings)
```
¯\_(ツ)_/¯

**Comment by roundhill** [comment]
> ¯\_(ツ)_/¯

Well you know, it's mostly warnings...

**Comment by beaucollins** [comment]
- No more eslint style issues.
- es6 modules
- Some shiny new tests for the auth component

**Comment by beaucollins** [comment]
@roundhill This should be good to go.

Everything uses es6 module syntax. All es6 source is now in `./src` and the `npm run postinstall` script transpiles it with `babel-core` and puts it in `./lib`.

**Comment by beaucollins** [comment]
I copied the `.eslintrc` file from [Automattic/wp-calypso](https://github.com/Automattic/wp-calypso/blob/master/.eslintrc)

**Comment by roundhill** [comment]
:shipit:

**Pull request merged**
